### ISSUE TITLE
スポンサーのロゴをクリックしても、スポンサーのコーポレートサイトが表示されない

### ISSUE THREAD

**Issue by urimaro** [rubykansai/kansai2017#26]
スポンサーのロゴをクリックしても、スポンサーのコーポレートサイトが表示されません。
リンクを設定した方が良いんじゃないかと思います。

**Comment by ogom** [comment]
リンク先のURLをスポンサーからリンクをしてよいかの許可が取れていません。また、どのURLにリンクするかが分かりません。

**Comment by urimaro** [comment]
一般的に、リンクを設定したくない理由は、以下の2点だと考えています。
- 関連していることを知られたくない
- アクセスが急増されると困る

「企業・団体名、ロゴ、紹介文を掲載しているけれどもリンクはNGかもしれない」と判断した決め手を教えてください 🤔 
URLについては、トップページではなく、採用ページを表示したいということも考えられるので確認します。

**Comment by urimaro** [comment]
Sponsor | URL
--- | ---
Agileware | http://agileware.jp
Ruby開発 | https://www.ruby-dev.jp/
Aiming | https://aiming-inc.com/
日本Rubyの会 | http://ruby-no-kai.org/
6VOX | http://6vox.com

スポンサーに確認が取れました。

**Comment by ogom** [comment]
どこにリンクをするのが正しいかはスポンサーの担当者に確認をするほうが確実だと思います。ロゴと紹介文を確認したときにurlも提示してもらうとよかったですね。

**Comment by urimaro** [comment]
PR更新しましたー
