### ISSUE TITLE
タイムテーブルの見た目について

### ISSUE THREAD

**Issue by znz** [rubykansai/kansai2017#36]
今のタイムテーブルにリニューアルされて最初に見たときに、時間と内容が同じように並んでいて、どっちの時間に対応するかわかりにくいと感じたのですが、もうちょっとわかりやすくならないでしょうか。

慣れてしまって今はそうでもないんですが、上から順番に見ている時は良いんですが、途中だけみた時とかわかりにくそうと感じます。

時間と内容は近づけて、次の時間との間はあけるとかすればわかりやすいのかもしれません。

**Comment by kmnhrn** [comment]
ご意見ありがとうございます。そして見づらくて申し訳ないです。
ちょうどタイムテーブルに、アバターなど追加作業しますので、
ご意見受けた箇所、見せ方変更するようにしますー！

**Comment by znz** [comment]
非常にわかりやすくなりました。対応ありがとうございました。
