### ISSUE TITLE
favicon.ico が Not Found みたいです

### ISSUE THREAD

**Issue by springaki** [rubykansai/kansai2017#4]
`https://rubykansai.github.io/favicon.ico` が `404 (Not Found)` になってました。
お知らせまで。

**Comment by kmnhrn** [comment]
お知らせありがとうございます！
OGPと一緒にまた追加しておきます。

**Comment by springaki** [comment]
😊

**Comment by ogom** [comment]
ファビコンのイメージを確認しました。 👍 
https://rubykansai.github.io/kansai2017/images/favicon.ico
