### ISSUE TITLE
発表者のスライドを公式サイトのタイムテーブルに追加する。

### ISSUE THREAD

**Issue by ogom** [rubykansai/kansai2017#43]
発表者のスライドのURL

* 須藤功平
   * https://slide.rabbit-shocker.org/authors/kou/kansai-rubykaigi-2017/
* 増井雄一郎
   * https://speakerdeck.com/masuidrive/18nian-derubykaraxue-ndakoto-guan-xi-rubyhui-yi-2017

**Comment by urimaro** [comment]
- kozo2さん(西田さん)
  - https://t.co/jRiLOrVwfq
- joker1007さん(橋立さん)
  - https://t.co/j6lLz2jjMA
- muryoimplさん(無量井さん)  
  ↓とのこと。
  > slideshareにログインできなくなってたので問い合わせ中。  
  > それ故、アップロードはしばらくおまちください。
- 伊藤淳一さん
  - https://t.co/Ifvv9mAS0Y
- yaslabさん(安川さん)
  - https://t.co/UxVztDstcl

**Comment by muryoimpl** [comment]
- muryoimpl
  - https://speakerdeck.com/muryoimpl/kansai-ruby-kaigi-2017

**Comment by znz** [comment]
#46 で全員分そろっているようにみえるので、誰かダブルチェックして、大丈夫そうなら close してください。
