### ISSUE TITLE
ゲスト講演の発表者の紹介

### ISSUE THREAD

**Issue by ogom** [rubykansai/kansai2017#6]
須藤功平さん、増井雄一郎さんの紹介文の原稿

**Comment by ogom** [comment]
須藤功平さん

株式会社クリアコードの代表取締役
Rubyのコミッターでもあり、有名な書籍であるリーダブルコードの解説の執筆者。
自身もOSS開発行っている傍ら、OSS開発を広めようとOSS Gateを立ち上げる。

* GitHub: https://github.com/kou
* Twitter: https://twitter.com/ktou
* Avatar: https://avatars.githubusercontent.com/kou

**Comment by ogom** [comment]
増井雄一郎さん

株式会社トレタのCTO
CTOという傍らで、色々なWebメディアや講演等の各所で姿を見せる。
「風呂グラマー」「IT芸人」と様々な代名詞で開発者から親しまれている。

* GitHub: https://github.com/masuidrive
* Twitter: https://twitter.com/masuidrive
* Avatar: https://avatars.githubusercontent.com/masuidrive

**Comment by chimame** [comment]
すいません。文言はこちらみたいです。

```
・須藤功平 株式会社クリアコードの代表取締役 社長
Ruby コミッター。有名な書籍「リーダブルコード」の解説文を執筆。
自身もOSS開発を行う一方、OSS開発を広めるための活動 OSS Gate を立ち上げる。

・増井雄一郎 株式会社トレタ CTO
CTOという傍らで、色々なWebメディアや講演などで活躍。 
「風呂グラマー」「IT芸人」とさまざまな代名詞で開発者から親しまれている。
```
