### ISSUE TITLE
チームのメンバー

### ISSUE THREAD

**Issue by ogom** [rubykansai/kansai2017#7]
主催者のメンバーリスト

**Comment by ogom** [comment]
主催者（アルファベット順）

* cuzic
* higaki
  * Avatar: https://s.gravatar.com/avatar/a8192f5a7b25ef32a983740ee8593bd3
* kmnhrn: ロゴ、ティザーサイト
* kusakabe
* murajun: 幹事
  * Avatar: https://www.gravatar.com/avatar/d8cd979e90361eb5ca5414dd15b35d0f
* ogom: 実行委員長
  * Avatar: https://avatars.githubusercontent.com/ogom
* spring_kuma
* rito
  * Avatar: https://avatars.githubusercontent.com/chimame
* urimaro
* znz
  * Avatar: https://avatars.githubusercontent.com/znz

アバターのリンクがない方は `no image` を表示します。

**Comment by ogom** [comment]
デザイナー

* kmnhrn: ロゴ、ティザーサイト

**Comment by ogom** [comment]
当日スタッフ

* yamada

**Comment by murajun1978** [comment]
avatar: https://www.gravatar.com/avatar/d8cd979e90361eb5ca5414dd15b35d0f

**Comment by higaki** [comment]
これでどうでしょうか
https://s.gravatar.com/avatar/99fdcba42f474bd3b805b8f723c16197

**Comment by znz** [comment]
gravatar のデフォルトサイズより github の方が高解像度のが出てきたので、これで。
https://avatars.githubusercontent.com/znz

**Comment by higaki** [comment]
gravatar は ?s=256 とかすると、おっきいの出るよね?

**Comment by znz** [comment]
gravatar で最大のサイズを探したり、登録した時の画像サイズがどうだったか考えるより、github の方を使う方が早かったので。

**Comment by ogom** [comment]
アバターは最終的にダウンロードされて、サイズやカラートーンが調整されるかもしれません。

**Comment by higaki** [comment]
github のやつに変えてみたけど、解像度低くて死んだ。
どっかに解像度高いのなかったかなぁ...

**Comment by ogom** [comment]
@kmnhrn アバターのサイズに指定はありますか？

**Comment by kmnhrn** [comment]
@ogom
特に指定はないです！
スタッフアイコンは今のところ100px以下（60〜80あたり）を考えていますので、それほど大きくなくても大丈夫です。

**Comment by springkuma** [comment]
遅ればせながら…
https://avatars1.githubusercontent.com/springkuma

**Comment by urimaro** [comment]
同じく遅ればせながら
https://s.gravatar.com/avatar/28f8545128369a677278b755e74d29df

gravatar変えたらGiHubのアイコンも変わっちゃった。

**Comment by cuzic** [comment]
いいアイコンないから、facebook のにしよかな。
https://scontent.xx.fbcdn.net/v/t1.0-1/c5.0.191.191/1912010_10152251423769704_1232870_n.jpg?oh=17e4238c5423748dfe20b574b2865051&oe=59A21E5F
