### ISSUE TITLE
スポンサーの紹介

### ISSUE THREAD

**Issue by ogom** [rubykansai/kansai2017#8]
スポンサーの紹介分の原稿

* スポンサーの種類
  * Gold: 1枠から2枠を予定
  * Silver: 2枠から4枠を予定
  * Drink:  1枠から2枠を予定

**Comment by ogom** [comment]
@kmnhrn スポンサーのロゴのサイズに指定はありますか？

**Comment by kmnhrn** [comment]
@ogom こちらでロゴが切れないようにリサイズさせていただくと思いますので、明確なサイズ指定はありませんが、
大きめという意味で縦横どちらか300px以上でいただければと思います。

**Comment by ogom** [comment]
* Gold
  * 株式会社Ruby開発
  * 株式会社アジャイルウェア
* Silver
  * 株式会社Aiming
  * 日本Rubyの会
* Drink
  * 株式会社6VOX

**Comment by ogom** [comment]
株式会社Ruby開発

```
株式会社Ruby開発は、Ruby on Railsをコア技術とし、クラウドを利用したアジャイル開発により、新規サービスを短期間で立ち上げ、継続的な機能改善・追加を得意としています。 ビジネスモデルを構築するため、サービスの企画・提案から、開発・運用・保守まで一貫して支援しています。
```

![ruby-dev](https://cloud.githubusercontent.com/assets/471923/24318756/daba5d48-114d-11e7-9029-6b0e8faafc88.jpg)

**Comment by ogom** [comment]
株式会社アジャイルウェア

```
株式会社アジャイルウェアは、アジャイル開発により価値を素早く提供する、Rubyのスペシャリストが集まる会社です。100%自社内でRailsによるWebシステム開発を行っており、自社開発したRails製プロジェクト管理ツールRedmineのプラグイン『Lychee Redmine』はわずか3年で170の企業に導入されています。開発者満足あってのお客様満足と考え、完全フレックス制でプログラマが最も働きやすい時間帯に仕事ができるよう、適材適所に努めています。
```

![agileware](https://cloud.githubusercontent.com/assets/471923/24318768/52922c9c-114e-11e7-91ab-2afc72a47e8d.jpg)

**Comment by ogom** [comment]
日本Rubyの会

```
日本Rubyの会は、Rubyの利用者の支援とRuby(とRubyのライブラリ)開発者の支援を目的とした一般社団法人です。現在は、ドキュメントの整備や、イベントへの参加協力等を中心に活動しています。
```

![ruby-no-kai-long](https://cloud.githubusercontent.com/assets/471923/24318785/b5c677be-114e-11e7-9896-65ad57ecfb60.png)

**Comment by ogom** [comment]
株式会社6VOX

```
```

**Comment by ogom** [comment]
株式会社Aiming
