### ISSUE TITLE
タイムテーブル

### ISSUE THREAD

**Issue by ogom** [rubykansai/kansai2017#9]
開催のプログラム

* 開催時間は10時から17時
* 基調講演の時間は50分で質疑応答が10分（2名）
* CFPの時間は30分で質疑応答が10分 (5,6名)
* お昼休みや休憩時間は、長い目に設定したい。

**Comment by ogom** [comment]
| 時間 | 分 | 内容 |    
|---|---|---|
| 09:30 - 10:00 | 30 | 受付 |
| 10:00 - 10:10 | 10 | オープニング |
| 10:10 - 11:10 | 60 | ゲスト講演 |
| 11:10 - 11:20 | 10 | 休憩 |
| 11:20 - 12:00 | 40 | CFP発表 |
| 12:00 - 13:00 | 60 | 休憩 |
| 13:00 - 13:10 | 10 | スポンサーLT |
| 13:10 - 13:20 | 10 | スポンサーLT |
| 13:20 - 14:00 | 40 | CFP発表 |
| 14:00 - 14:10 | 10 | 休憩 |
| 14:10 - 14:50 | 40 | CFP発表 |
| 14:50 - 15:00 | 10 | 集合写真 |
| 15:00 - 15:40 | 40 | CFP発表 |
| 15:40 - 15:50 | 10 | 休憩 |
| 15:50 - 16:50 | 60 | ゲスト講演 |
| 16:50 - 17:00 | 10 | クロージング |

(ゲスト講演とCFP発表には10分の質疑応答を含む)

**Comment by ogom** [comment]
* 発表者を6人にする案
* 質疑応答は休憩時間にするほうが、発表者と身近に話せてよいかもという知見

| 時間 | 分 | 内容 |    
|---|---|---|
| 09:30 - 10:00 | 30 | 受付 |
| 10:00 - 10:10 | 10 | オープニング |
| 10:10 - 10:20 | 10 | スポンサーLT |
| 10:20 - 11:10 | 50 | ゲスト講演 |
| 11:10 - 11:20 | 10 | 休憩 |
| 11:20 - 11:50 | 30 | 発表１ |
| 11:50 - 12:50 | 60 | 休憩 |
| 12:50 - 13:20 | 30 | 発表２ |
| 13:20 - 13:50 | 30 | 発表３ |
| 13:50 - 14:00 | 10 | 休憩 |
| 14:00 - 14:30 | 30 | 発表４ |
| 14:30 - 15:00 | 30 | 発表５ |
| 15:00 - 15:10 | 10 | 休憩 |
| 15:10 - 15:40 | 30 | 発表６ |
| 15:40 - 15:50 | 10 | 集合写真 |
| 15:50 - 16:00 | 10 | スポンサーLT |
| 16:00 - 16:50 | 50 | ゲスト講演 |
| 16:50 - 17:00 | 10 | クロージング |

**Comment by ogom** [comment]
| 時間 | 分 | 内容 | 発表者 | タイトル |
|---|---|---|---| - |
| 09:30 - 10:00 | 30 | 受付 | - | - |
| 10:00 - 10:10 | 10 | オープニング | - | - |
| 10:10 - 11:10 | 60 | 基調講演 | 須藤功平 | - |
| 11:10 - 11:20 | 10 | 休憩 | - | - |
| 11:20 - 11:50 | 30 | 講演 | kozo2 | Rubyでデータサイエンスを行うための取り組み
| 11:50 - 12:50 | 60 | 休憩 | - | - |
| 12:50 - 13:20 | 30 | 講演 | 田中宏基 | エンタープライズRubyOnRails  エンプラでぶち当たった2つの壁と突破法 
| 13:20 - 13:50 | 30 | 講演 | joker1007 | Rubygem開発の流儀
| 13:50 - 14:00 | 10 | 休憩 | - | - |
| 14:00 - 14:30 | 30 | 講演 |  muryoimpl | コミュニティ文化の取り込みとその機会で得た知見
| 14:30 - 15:00 | 30 | 講演 |  伊藤淳一 | Rubyistと技術記事 ～なぜ書くの？どう書くの？何が起きるの？～
| 15:00 - 15:10 | 10 | 休憩 | - | - |
| 15:10 - 15:40 | 30 | 講演 | yasulab | 子どものためのプログラミング道場「CoderDojo」を支えるRails CMSの活用事例 
| 15:40 - 15:50 | 10 | 集合写真 | - | - |
| 15:50 - 16:50 | 60 | 基調講演 | 増井雄一郎 | - |
| 16:50 - 17:00 | 10 | クロージング | - | - |

**Comment by ogom** [comment]
ティザーサイトには `分` の公開は不要です。

**Comment by higaki** [comment]
確か kozo2 さんから、内容説明文の差し替え依頼が来てたと思いますけど、あれはどういう対応すればいいんでしょう。

**Comment by ogom** [comment]
@higaki  doorkeeper で編集しました。

**Comment by urimaro** [comment]
発表者の申込み内容って、まんま掲載する予定なんでしょうか？ 🤔

**Comment by ogom** [comment]
06  では発表内容が解ると参加しやすいと意見があったのでタイトルだけを掲載していました。
http://regional.rubykaigi.org/kansai06/

2017 もタイトルだけの掲載の予定です。

**Comment by cuzic** [comment]
発表内容だけの掲載でいいと思います
